### ISSUE TITLE
write() argument must be str, not bytes

### ISSUE THREAD

**Issue by andrewhowdencom** [geerlingguy/ansible-role-php-xdebug#50]
HOlaa, Just hit

> TASK [geerlingguy.php-xdebug : Untar Xdebug.] **********************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading https://xdebug.org/files/xdebug-2.5.0.tgz, write() argument must be str, not bytes"}

I think it's because it's executing with python3?

**Comment by andrewhowdencom** [comment]
Related: https://github.com/ansible/ansible-modules-core/issues/5791

**Comment by andrewhowdencom** [comment]
No good in 2.3.0.0 solved in 

```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

**Comment by geerlingguy** [comment]
Good catch! Yeah, there are a few Python 3 bugs still lurking here and there; it seems one focus for Ansible 2.4 is to get almost everything working under 3.x.
